# Generated by Django 6.0.6 on 2026-06-12 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(db_column='id_produto', primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(db_column='nome_produto', max_length=45)),
                ('categoria', models.CharField(db_column='categoria', max_length=20)),
                ('descricao', models.CharField(db_column='descricao', max_length=45)),
                ('estado_conservacao', models.CharField(db_column='estado_conservacao', max_length=10)),
                ('servico', models.ForeignKey(db_column='servico_idservico', on_delete=django.db.models.deletion.CASCADE, to='Servicos.servico')),
            ],
            options={
                'db_table': 'produto',
            },
        ),
    ]
