# Generated by Django 6.0.6 on 2026-06-12 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catalogo', '0001_initial'),
        ('Trocas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='troca',
            field=models.ForeignKey(db_column='troca_idtroca', on_delete=django.db.models.deletion.CASCADE, to='Trocas.troca'),
        ),
    ]
