# Generated by Django 6.0.6 on 2026-06-12 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catalogo', '0001_initial'),
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoTroca',
            fields=[
                ('id_solicitacao', models.AutoField(db_column='idSolicitacao', primary_key=True, serialize=False)),
                ('data_solicitacao', models.DateTimeField(db_column='Data_solicitacao')),
                ('status_solicitacao', models.CharField(db_column='Status_solicitacao', max_length=45)),
                ('produto', models.ForeignKey(db_column='produto_idProduto', on_delete=django.db.models.deletion.CASCADE, to='Catalogo.produto')),
                ('usuario', models.ForeignKey(db_column='usuario_idUsuario', on_delete=django.db.models.deletion.CASCADE, to='Cliente.usuario')),
            ],
            options={
                'db_table': 'solicitacao_troca',
            },
        ),
        migrations.CreateModel(
            name='Troca',
            fields=[
                ('id_troca', models.AutoField(db_column='idtroca', primary_key=True, serialize=False)),
                ('data_troca', models.DateTimeField(db_column='Data_troca')),
                ('status_troca', models.CharField(db_column='status_troca', max_length=45)),
                ('usuario_proponente', models.ForeignKey(db_column='usuario_idUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='trocas_propostas', to='Cliente.usuario')),
                ('usuario_receptor', models.ForeignKey(db_column='usuario_idUsuario1', on_delete=django.db.models.deletion.CASCADE, related_name='trocas_recebidas', to='Cliente.usuario')),
            ],
            options={
                'db_table': 'troca',
            },
        ),
    ]
