# Generated by Django 6.0.6 on 2026-06-12 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(db_column='idperfil', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='descricao_perfil', max_length=45, null=True)),
            ],
            options={
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=45)),
                ('email', models.CharField(db_column='Email', max_length=45)),
                ('senha', models.IntegerField(db_column='Senha')),
                ('telefone', models.IntegerField(blank=True, db_column='Telefone', null=True)),
                ('saldo_ecopoints', models.CharField(blank=True, db_column='SaldoEcoPoins', max_length=45, null=True)),
                ('reputcao', models.CharField(blank=True, db_column='Reputcao', max_length=45, null=True)),
                ('perfil', models.ForeignKey(db_column='Perfil_idPerfil', on_delete=django.db.models.deletion.CASCADE, to='Cliente.perfil')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
