# Generated by Django 6.0.6 on 2026-06-12 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id_servico', models.AutoField(db_column='idservico', primary_key=True, serialize=False)),
                ('desc_servico', models.CharField(blank=True, db_column='Desc_servico', max_length=45, null=True)),
                ('nome_servico', models.CharField(db_column='nome_servico', max_length=15)),
                ('valor_servico', models.CharField(db_column='valor_servico', max_length=10)),
            ],
            options={
                'db_table': 'servico',
            },
        ),
        migrations.CreateModel(
            name='ServicoHasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.ForeignKey(db_column='Servicos_idservico', on_delete=django.db.models.deletion.CASCADE, to='Servicos.servico')),
                ('usuario', models.ForeignKey(db_column='Usuario_idUsuario', on_delete=django.db.models.deletion.CASCADE, to='Cliente.usuario')),
            ],
            options={
                'db_table': 'servico_has_usuario',
                'unique_together': {('usuario', 'servico')},
            },
        ),
    ]
